/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.rit;

import com.company.atvcoord.AtvCoordView;
import com.mycompany.alunos.AlunoView;
import com.mycompany.artigos.ArtigosView;
import com.mycompany.disciplina.DisciplinaView;
import com.mycompany.professor.ProfessorCrudView;

/**
 *
 * @author washington.riega
 */
public class RitView extends javax.swing.JFrame {

    /**
     * Creates new form RitCrud
     * @param id
     */
    
    private Integer professor_id;
    
    public RitView(Integer id) {
        initComponents();
        professor_id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnDisciplinas = new javax.swing.JButton();
        btnAlunos = new javax.swing.JButton();
        btnArtigos = new javax.swing.JButton();
        btnAtividades = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(986, 232));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Relatórios Individuais de Trabalho");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(340, 10, 294, 25);

        btnDisciplinas.setText("Disciplinas Ministradas");
        btnDisciplinas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisciplinasActionPerformed(evt);
            }
        });
        getContentPane().add(btnDisciplinas);
        btnDisciplinas.setBounds(126, 114, 149, 49);

        btnAlunos.setText("Alunos Orientados");
        btnAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlunosActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlunos);
        btnAlunos.setBounds(307, 114, 129, 49);

        btnArtigos.setText("Artigos Publicados");
        btnArtigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtigosActionPerformed(evt);
            }
        });
        getContentPane().add(btnArtigos);
        btnArtigos.setBounds(478, 114, 129, 49);

        btnAtividades.setText("Atividades de Coordenação");
        btnAtividades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtividadesActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtividades);
        btnAtividades.setBounds(659, 114, 176, 49);

        btnVoltar.setText("<");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btnVoltar);
        btnVoltar.setBounds(0, 4, 50, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\washington.riega\\OneDrive - Venturus iTriad\\Área de Trabalho\\UFAM\\TAP\\TP1\\JavaApplication1\\Background_Banner2_Desktop.png")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1, -4, 1880, 250);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDisciplinasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDisciplinasActionPerformed
        // TODO add your handling code here:
        DisciplinaView tela = new DisciplinaView(professor_id);
        dispose();
        tela.setSize(957, 712);
        tela.setVisible(true);
    }//GEN-LAST:event_btnDisciplinasActionPerformed

    private void btnAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlunosActionPerformed
        // TODO add your handling code here:
        AlunoView tela = new AlunoView(professor_id);
        dispose();
        tela.setSize(957, 712);
        tela.setVisible(true);
    }//GEN-LAST:event_btnAlunosActionPerformed

    private void btnArtigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtigosActionPerformed
        // TODO add your handling code here:
        ArtigosView tela = new ArtigosView(professor_id);
        dispose();
        tela.setSize(957, 712);
        tela.setVisible(true);
    }//GEN-LAST:event_btnArtigosActionPerformed

    private void btnAtividadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtividadesActionPerformed
        // TODO add your handling code here:
        AtvCoordView tela = new AtvCoordView(professor_id);
        dispose();
        tela.setSize(957, 712);
        tela.setVisible(true);
    }//GEN-LAST:event_btnAtividadesActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        ProfessorCrudView tela = new ProfessorCrudView();
        dispose();
        tela.setSize(682, 546);
        tela.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RitView(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlunos;
    private javax.swing.JButton btnArtigos;
    private javax.swing.JButton btnAtividades;
    private javax.swing.JButton btnDisciplinas;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
